<?php
/**
 * BatchTransactionsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * BatchTransactionsApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BatchTransactionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation listBatchTransactions
     *
     * List Batch Transactions
     *
     * @param  int $limit Number of records to retrieve. Up to 200. (optional, default to 10)
     * @param  int $offset Number of records to offset. Required for pagination. (optional, default to 0)
     * @param  string $account_id Bank, Card or Wallet Account ID. (optional)
     * @param  string $batch_id Batch ID. This appears on a bank reference. (optional)
     * @param  string $item_id Item ID (optional)
     * @param  string $transaction_type The type of transaction. Options for querying are: payment, refund, disbursement, fee, deposit, withdrawal. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $transaction_type_method The method the transaction was carried out with. Options for querying are: direct_debit, credit_card, npp, bpay, wire_transfer, wallet_account_transfer, direct_credit, misc. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $direction Direction of the transaction. Options are debit, credit (optional)
     * @param  string $created_before Date and time in ISO 8601 format the item(s) were created before (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $created_after Date and time in ISO 8601 format the item(s) were created after (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $disbursement_bank The bank used for disbursing the payment. Please use a default value of &#x60;any&#x60; (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ListBatchTransactions
     */
    public function listBatchTransactions($limit = 10, $offset = 0, $account_id = null, $batch_id = null, $item_id = null, $transaction_type = null, $transaction_type_method = null, $direction = null, $created_before = null, $created_after = null, $disbursement_bank = null)
    {
        list($response) = $this->listBatchTransactionsWithHttpInfo($limit, $offset, $account_id, $batch_id, $item_id, $transaction_type, $transaction_type_method, $direction, $created_before, $created_after, $disbursement_bank);
        return $response;
    }

    /**
     * Operation listBatchTransactionsWithHttpInfo
     *
     * List Batch Transactions
     *
     * @param  int $limit Number of records to retrieve. Up to 200. (optional, default to 10)
     * @param  int $offset Number of records to offset. Required for pagination. (optional, default to 0)
     * @param  string $account_id Bank, Card or Wallet Account ID. (optional)
     * @param  string $batch_id Batch ID. This appears on a bank reference. (optional)
     * @param  string $item_id Item ID (optional)
     * @param  string $transaction_type The type of transaction. Options for querying are: payment, refund, disbursement, fee, deposit, withdrawal. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $transaction_type_method The method the transaction was carried out with. Options for querying are: direct_debit, credit_card, npp, bpay, wire_transfer, wallet_account_transfer, direct_credit, misc. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $direction Direction of the transaction. Options are debit, credit (optional)
     * @param  string $created_before Date and time in ISO 8601 format the item(s) were created before (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $created_after Date and time in ISO 8601 format the item(s) were created after (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $disbursement_bank The bank used for disbursing the payment. Please use a default value of &#x60;any&#x60; (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ListBatchTransactions, HTTP status code, HTTP response headers (array of strings)
     */
    public function listBatchTransactionsWithHttpInfo($limit = 10, $offset = 0, $account_id = null, $batch_id = null, $item_id = null, $transaction_type = null, $transaction_type_method = null, $direction = null, $created_before = null, $created_after = null, $disbursement_bank = null)
    {
        $request = $this->listBatchTransactionsRequest($limit, $offset, $account_id, $batch_id, $item_id, $transaction_type, $transaction_type_method, $direction, $created_before, $created_after, $disbursement_bank);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\ListBatchTransactions' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ListBatchTransactions', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\ListBatchTransactions';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ListBatchTransactions',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listBatchTransactionsAsync
     *
     * List Batch Transactions
     *
     * @param  int $limit Number of records to retrieve. Up to 200. (optional, default to 10)
     * @param  int $offset Number of records to offset. Required for pagination. (optional, default to 0)
     * @param  string $account_id Bank, Card or Wallet Account ID. (optional)
     * @param  string $batch_id Batch ID. This appears on a bank reference. (optional)
     * @param  string $item_id Item ID (optional)
     * @param  string $transaction_type The type of transaction. Options for querying are: payment, refund, disbursement, fee, deposit, withdrawal. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $transaction_type_method The method the transaction was carried out with. Options for querying are: direct_debit, credit_card, npp, bpay, wire_transfer, wallet_account_transfer, direct_credit, misc. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $direction Direction of the transaction. Options are debit, credit (optional)
     * @param  string $created_before Date and time in ISO 8601 format the item(s) were created before (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $created_after Date and time in ISO 8601 format the item(s) were created after (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $disbursement_bank The bank used for disbursing the payment. Please use a default value of &#x60;any&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listBatchTransactionsAsync($limit = 10, $offset = 0, $account_id = null, $batch_id = null, $item_id = null, $transaction_type = null, $transaction_type_method = null, $direction = null, $created_before = null, $created_after = null, $disbursement_bank = null)
    {
        return $this->listBatchTransactionsAsyncWithHttpInfo($limit, $offset, $account_id, $batch_id, $item_id, $transaction_type, $transaction_type_method, $direction, $created_before, $created_after, $disbursement_bank)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listBatchTransactionsAsyncWithHttpInfo
     *
     * List Batch Transactions
     *
     * @param  int $limit Number of records to retrieve. Up to 200. (optional, default to 10)
     * @param  int $offset Number of records to offset. Required for pagination. (optional, default to 0)
     * @param  string $account_id Bank, Card or Wallet Account ID. (optional)
     * @param  string $batch_id Batch ID. This appears on a bank reference. (optional)
     * @param  string $item_id Item ID (optional)
     * @param  string $transaction_type The type of transaction. Options for querying are: payment, refund, disbursement, fee, deposit, withdrawal. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $transaction_type_method The method the transaction was carried out with. Options for querying are: direct_debit, credit_card, npp, bpay, wire_transfer, wallet_account_transfer, direct_credit, misc. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $direction Direction of the transaction. Options are debit, credit (optional)
     * @param  string $created_before Date and time in ISO 8601 format the item(s) were created before (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $created_after Date and time in ISO 8601 format the item(s) were created after (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $disbursement_bank The bank used for disbursing the payment. Please use a default value of &#x60;any&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listBatchTransactionsAsyncWithHttpInfo($limit = 10, $offset = 0, $account_id = null, $batch_id = null, $item_id = null, $transaction_type = null, $transaction_type_method = null, $direction = null, $created_before = null, $created_after = null, $disbursement_bank = null)
    {
        $returnType = '\OpenAPI\Client\Model\ListBatchTransactions';
        $request = $this->listBatchTransactionsRequest($limit, $offset, $account_id, $batch_id, $item_id, $transaction_type, $transaction_type_method, $direction, $created_before, $created_after, $disbursement_bank);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listBatchTransactions'
     *
     * @param  int $limit Number of records to retrieve. Up to 200. (optional, default to 10)
     * @param  int $offset Number of records to offset. Required for pagination. (optional, default to 0)
     * @param  string $account_id Bank, Card or Wallet Account ID. (optional)
     * @param  string $batch_id Batch ID. This appears on a bank reference. (optional)
     * @param  string $item_id Item ID (optional)
     * @param  string $transaction_type The type of transaction. Options for querying are: payment, refund, disbursement, fee, deposit, withdrawal. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $transaction_type_method The method the transaction was carried out with. Options for querying are: direct_debit, credit_card, npp, bpay, wire_transfer, wallet_account_transfer, direct_credit, misc. For returned values please refer here: [Enumeration Values](https://developer.assemblypayments.com/docs/enumeration-values) for the full list (optional)
     * @param  string $direction Direction of the transaction. Options are debit, credit (optional)
     * @param  string $created_before Date and time in ISO 8601 format the item(s) were created before (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $created_after Date and time in ISO 8601 format the item(s) were created after (e.g. 2020-02-27T23:54:59Z) (optional)
     * @param  string $disbursement_bank The bank used for disbursing the payment. Please use a default value of &#x60;any&#x60; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listBatchTransactionsRequest($limit = 10, $offset = 0, $account_id = null, $batch_id = null, $item_id = null, $transaction_type = null, $transaction_type_method = null, $direction = null, $created_before = null, $created_after = null, $disbursement_bank = null)
    {
        if ($limit !== null && $limit > 200) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling BatchTransactionsApi.listBatchTransactions, must be smaller than or equal to 200.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling BatchTransactionsApi.listBatchTransactions, must be bigger than or equal to 1.');
        }

        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling BatchTransactionsApi.listBatchTransactions, must be bigger than or equal to 0.');
        }


        $resourcePath = '/batch_transactions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($limit !== null) {
            if('form' === 'form' && is_array($limit)) {
                foreach($limit as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['limit'] = $limit;
            }
        }
        // query params
        if ($offset !== null) {
            if('form' === 'form' && is_array($offset)) {
                foreach($offset as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['offset'] = $offset;
            }
        }
        // query params
        if ($account_id !== null) {
            if('form' === 'form' && is_array($account_id)) {
                foreach($account_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['account_id'] = $account_id;
            }
        }
        // query params
        if ($batch_id !== null) {
            if('form' === 'form' && is_array($batch_id)) {
                foreach($batch_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['batch_id'] = $batch_id;
            }
        }
        // query params
        if ($item_id !== null) {
            if('form' === 'form' && is_array($item_id)) {
                foreach($item_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['item_id'] = $item_id;
            }
        }
        // query params
        if ($transaction_type !== null) {
            if('form' === 'form' && is_array($transaction_type)) {
                foreach($transaction_type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['transaction_type'] = $transaction_type;
            }
        }
        // query params
        if ($transaction_type_method !== null) {
            if('form' === 'form' && is_array($transaction_type_method)) {
                foreach($transaction_type_method as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['transaction_type_method'] = $transaction_type_method;
            }
        }
        // query params
        if ($direction !== null) {
            if('form' === 'form' && is_array($direction)) {
                foreach($direction as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['direction'] = $direction;
            }
        }
        // query params
        if ($created_before !== null) {
            if('form' === 'form' && is_array($created_before)) {
                foreach($created_before as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['created_before'] = $created_before;
            }
        }
        // query params
        if ($created_after !== null) {
            if('form' === 'form' && is_array($created_after)) {
                foreach($created_after as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['created_after'] = $created_after;
            }
        }
        // query params
        if ($disbursement_bank !== null) {
            if('form' === 'form' && is_array($disbursement_bank)) {
                foreach($disbursement_bank as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['disbursement_bank'] = $disbursement_bank;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation showBatchTransaction
     *
     * Show Batch Transaction
     *
     * @param  string $id Transaction ID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\SingleBatchTransaction
     */
    public function showBatchTransaction($id)
    {
        list($response) = $this->showBatchTransactionWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation showBatchTransactionWithHttpInfo
     *
     * Show Batch Transaction
     *
     * @param  string $id Transaction ID (required)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\SingleBatchTransaction, HTTP status code, HTTP response headers (array of strings)
     */
    public function showBatchTransactionWithHttpInfo($id)
    {
        $request = $this->showBatchTransactionRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\SingleBatchTransaction' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\SingleBatchTransaction', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\SingleBatchTransaction';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\SingleBatchTransaction',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation showBatchTransactionAsync
     *
     * Show Batch Transaction
     *
     * @param  string $id Transaction ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function showBatchTransactionAsync($id)
    {
        return $this->showBatchTransactionAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation showBatchTransactionAsyncWithHttpInfo
     *
     * Show Batch Transaction
     *
     * @param  string $id Transaction ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function showBatchTransactionAsyncWithHttpInfo($id)
    {
        $returnType = '\OpenAPI\Client\Model\SingleBatchTransaction';
        $request = $this->showBatchTransactionRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'showBatchTransaction'
     *
     * @param  string $id Transaction ID (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function showBatchTransactionRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling showBatchTransaction'
            );
        }

        $resourcePath = '/batch_transactions/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }
        // this endpoint requires OAuth (access token)
        if ($this->config->getAccessToken() !== null) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
